### ISSUE TITLE
Improve exception reporting

### ISSUE THREAD

**Issue by sanity** [kwebio/core#24]
```
[ktor-pool-1-thread-14] INFO io.kweb.demo.Joker - Create clicked
[ForkJoinPool.commonPool-worker-1] ERROR io.kweb.WebBrowser -         at com.github.sanity.shoebox.OrderedViewSet$1.invoke(OrderedViewSet.kt:24)
        at com.github.sanity.shoebox.OrderedViewSet$1.invoke(OrderedViewSet.kt:8)
        at com.github.sanity.shoebox.View$1.invoke(View.kt:27)
        at com.github.sanity.shoebox.View$1.invoke(View.kt:12)
        at com.github.sanity.shoebox.Shoebox.set(Shoebox.kt:78)
        at io.kweb.demo.JokerKt$main$1$$special$$inlined$route$lambda$1$1$3$1$1.doResume(joker.kt:89)
```

is thrown by:

```
                is BinarySearchResult.Exact -> throw RuntimeException("Listener called for value already in list ($keyValue)")
```
But the exception itself is not included in the output (from kweb-demo)

**Comment by sanity** [comment]
Fixed in master
