### ISSUE TITLE
Exception running todoApp.kt

### ISSUE THREAD

**Issue by sanity** [kwebio/core#42]
Reported [on reddit](https://www.reddit.com/r/programming/comments/a4dtp2/kweb_a_new_approach_to_building_rich_webapps_in/ebffltu/):

```
[pool-1-thread-1] INFO se.unir.kotlin.App - Rendering Add Item button
[qtp913190639-16] ERROR ktor.application - Websocket handler failed
java.lang.NoSuchMethodError: com.github.salomonbrys.kotson.GsonBuilderKt.removeTypeWildcards(Ljava/lang/reflect/Type;)Ljava/lang/reflect/Type;
    at io.kweb.Kweb$4$2$6.invokeSuspend(Kweb.kt:494)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
    at java.lang.Thread.run(Thread.java:748)
```

Dependencies looks ok:

```
<dependency>
  <groupId>com.github.kwebio</groupId>
  <artifactId>core</artifactId>
  <version>0.3.12</version>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-simple</artifactId>
  <version>1.7.25</version>
</dependency>
```

**Comment by sanity** [comment]
Kotson was 2.3.0 but current release is 2.5.0.  I've updated it in release 0.3.13 to see if that helps.  Also checking with Kotson devs.
