### ISSUE TITLE
Fix possible Firefox routing bug

### ISSUE THREAD

**Issue by sanity** [kwebio/core#50]
reported by: @MrPowerGamerBR

Also, I think I found a bug (only happens in Firefox)

If I'm accessing the website (example: 127.0.0.1/path), if I change the URL on the address bar and change it to 127.0.0.1/anotherpath, it doesn't redirect it stays on the 127.0.0.1/path
it works on chromium.

**Comment by alkoclick** [comment]
I am also experiencing this, while using Firefox Quantum 67.0 on Ubuntu

**Comment by sanity** [comment]
Could you describe the steps to reproduce in more detail?  I wasn't able to reproduce @MrPowerGamerBR's issue locally.

**Comment by sanity** [comment]
Will investigate.

**Comment by alkoclick** [comment]
The following fails for me on my home desktop, also running Firefox Quantum 67.0 on Ubuntu but a different version (18.04)

By fails I mean:
-> The link preview displays properly when I hover
-> If I ctrl-click it, the new tab opens in the correct url
-> If I normally click it, the page reloads but nothing happens, the url doesn't change
-> If I change the url manually in this page, it reloads and remains in the same place (even if I would navigate to a valid url in the page)
-> Shit I just realized that it also stops me if I try to go to another page, like google.com. My browser tab is literally imprisoned in this url!
```
fun main() {
    Kweb(port = 16097, plugins = listOf(BootstrapUIPlugin())) {
        doc.body.new {
            route {
                path("/aPath") { 
                    h1().text("The page changed")
                }
                path("/") {
                    a(href = "/aPath").text("Click me!")
                }
            }
        }
    }
}

```

**Comment by ethanmdavidson** [comment]
From the firefox console, when you click the link:
```
Navigated to http://localhost:16097/aPath
Socket closed localhost:16097:138:29
WebSocket was closed without a reason specified 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
localhost:16097:146:29
Forcing page reload localhost:16097:148:29
Navigated to http://localhost:16097/
```
It tries to navigate, which closes the websocket, firing the onClose event [which reloads the current page](https://github.com/kwebio/core/blob/master/src/main/resources/io/kweb/kweb_bootstrap.html#L149), overriding the navigation.

Apparently, the proper way to handle this is to attempt to reconnect if [CloseEvent.wasClean](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) is true. See [this stackoverflow answer](https://stackoverflow.com/questions/10965720/should-websocket-onclose-be-triggered-by-user-navigation-or-refresh)

Should be fixed in b98ccc204b73804f90f6f4b3c45020c09731de37, please see if it works for you.

I'll write a test to cover this and figure out how to have selenium run the tests with firefox as well as chrome.

**Comment by alkoclick** [comment]
How can I test if it is fixed? Please don't tell me to build from source and include in my project :P Is the new version on JitPack?

**Comment by ethanmdavidson** [comment]
Yeah, it looks like JitPack allows you to use the commit hash as a dependency: https://jitpack.io/#kwebio/core/b98ccc204b

try changing your kweb dependency to `com.github.kwebio:core:b98ccc204b`

I've never tried this before so let me know if it works.

**Comment by alkoclick** [comment]
I'm using gradle for dependency management and build automation. It actually managed to pull it using

```
dependencies {
    compile 'com.github.kwebio:core:b98ccc204b'
}
```

but then I'm getting a different problem (which may need its own issue probably)

```
e: java.lang.IllegalStateException: Visibility is unknown yet
	at org.jetbrains.kotlin.descriptors.Visibilities$7.isVisible(Visibilities.java:257)
	at org.jetbrains.kotlin.descriptors.Visibilities.findInvisibleMember(Visibilities.java:335)
	at org.jetbrains.kotlin.descriptors.Visibilities.isVisibleIgnoringReceiver(Visibilities.java:306)
	at org.jetbrains.kotlin.resolve.OverridingUtil.isVisibleForOverride(OverridingUtil.java:427)
	at org.jetbrains.kotlin.resolve.OverridingUtil.extractAndBindOverridesForMember(OverridingUtil.java:442)
	at org.jetbrains.kotlin.resolve.OverridingUtil.generateOverridesInFunctionGroup(OverridingUtil.java:418)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.generateFakeOverrides(LazyClassMemberScope.kt:145)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getNonDeclaredFunctions(LazyClassMemberScope.kt:209)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.doGetFunctions(AbstractLazyMemberScope.kt:103)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$doGetFunctions(AbstractLazyMemberScope.kt:36)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:48)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:36)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:440)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:515)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedFunctions(AbstractLazyMemberScope.kt:84)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedFunctions(LazyClassMemberScope.kt:188)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitNamedFunction(LazyDeclarationResolver.kt:125)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitNamedFunction(LazyDeclarationResolver.kt:94)
	at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:50)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:94)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:91)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.createFunctionDescriptors(LazyTopDownAnalyzer.kt:282)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:204)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:60)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:111)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:384)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:70)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:375)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:131)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:387)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:237)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:37)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:79)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:91)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:601)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:455)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1027)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1069)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1026)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:454)
	at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by alkoclick** [comment]
Alright, can confirm fix works as expected! :)

**Comment by sanity** [comment]
Rolling out 0.4.19 in a minute which will include this fix.  Thanks guys.
